### ISSUE TITLE
Obo term for ion mobility based fractionation

### ISSUE THREAD

**Issue by Cajac102** [PRIDE-Utilities/pride-ontology#102]
Hello,

I'm currently annotating the SDRF for [this project](https://www.nature.com/articles/s41597-020-00724-7) ([PXD020785](https://www.ebi.ac.uk/pride/archive/projects/PXD020785)).  I'm wondering what term I should use for the fractions separated by Differential Mobility Separation on a SelexION device. Can you help me here?

Kind regards,
Caro

**Comment by ypriverol** [comment]
I think we can use the following term in the ontology: `SelexION mobility separation` we will add it to the ontology.
