### ISSUE TITLE
BioPortal submission

### ISSUE THREAD

**Issue by mkuhring** [PRIDE-Utilities/pride-ontology#5]
I was wondering if you would mind adding the PRIDE ontology to [BioPortal](bioportal.bioontology.org)? Or if there is a specific reason it is not added yet? I know the ontology is well accessible via your own OLS, but we are currently using the ISAcreator from the [ISA-tools suite](isa-tools.org) to manage our metadata. And as far as I'm aware it only connects with BioPortal. I think adding the PRIDE ontology to BioPortal would also probably benefit your reach and application. I would be glad to add it myself, if I get the permission to do so.

**Comment by ypriverol** [comment]
Thanks @mkuhring for contacting us. This is a good idea. You are free to add it. But we have an ongoing discussion in PSI-MS to merge this ontology with PSI-MS ontology. But for now would be great and really useful goal.

**Comment by mkuhring** [comment]
Thanks a lot, I will add it. Merging the two ontologies sounds also really interesting.

**Comment by ypriverol** [comment]
Again this will not happen soon, then having the Ontology inside BioPortal would be great. I will close this issue, let us know How it goes. Thanks again!!!

**Comment by mkuhring** [comment]
The ontology is now available at BioPortal: [https://bioportal.bioontology.org/ontologies/PRIDE](https://bioportal.bioontology.org/ontologies/PRIDE)

Please tell me, if you have any change requests regarding the details/metadata. And do you by chance use version numbers or names for your ontology? Otherwise I would simply number the submissions starting with 1, as many of the other ontologies do as well.
