### ISSUE TITLE
Problem with tag

### ISSUE THREAD

**Issue by ypriverol** [PRIDE-Utilities/pride-ontology#50]
This tag `Human Proteome Project, Sars-CoV-2, Covid-19` is the combination of three existing tags. Can we remove it. @deeptijk @javizca 

https://github.com/PRIDE-Utilities/pride-ontology/blob/master/pride-annotations/project-tags.csv#L31

**Comment by javizca** [comment]
Yes, they should be separate ones. I guess this has been caused by a copy/paste issue?

**Comment by ypriverol** [comment]
@sureshhewabi remove the tag.

**Comment by deeptijk** [comment]
Yes, looks like copy-paste mistake. Can we also add one more TAG in this list. Although it is present in the PX Tool but it's not here in the list. TAG name is "EPIC-XS" .

**Comment by sureshhewabi** [comment]
Thanks everyone. From now onwards, you can add new tags to this file from Pull Request
