### ISSUE TITLE
syntax error in pride_cv.obo

### ISSUE THREAD

**Issue by janelomax** [PRIDE-Utilities/pride-ontology#53]
The part_of syntax for these terms is incorrect:

[Term]
id: PRIDE:0000593
name: CID collision energy
def: "CID collision energy"
is_a: MS:1000045 ! collision energy
part_of: id: PRIDE:0000591 ! CID

[Term]
id: PRIDE:0000594
name: HCD collision energy
def: "HCD collision energy"
is_a: MS:1000045 ! collision energy
part_of: id: PRIDE:0000590 ! HCD

[Term]
id: PRIDE:0000595
name: EThcD collision energy
def: "EThcD collision energy"
is_a: MS:1000045 ! collision energy
part_of: id: PRIDE:0000589 ! EThcD

[Term]
id: PRIDE:0000596
name: ETciD collision energy
def: "ETciD collision energy"
is_a: MS:1000045 ! collision energy
part_of: id: PRIDE:0000592 ! ETciD

correct syntax should be:

`relationship: part_of PRIDE:0000591 ! CID`

**Comment by ypriverol** [comment]
Thanks for reporting the issue @janelomax. Can you take a look to the PR #55
