### ISSUE TITLE
Addition of TMT channels to PRIDE controlled vocabulary: 133N, 133C, 134N

### ISSUE THREAD

**Issue by ostr0103** [PRIDE-Utilities/pride-ontology#70]
Hello,

Can you add TMT channels, TMT133N, TMT133C and TMT134N to the accepted TMT labels within the PRIDE controlled vocabulary?  I am using a TMT16plex which has additional channels not found in the ontology at this time.

Thank you,

Danielle Weise

**Comment by ypriverol** [comment]
Already created in #71

**Comment by ostr0103** [comment]
Hi Yasset,

I went to submit my SDRF with the 133N, 133C and 134N labels and it still
says "invalid SDRF file detected".  The error in the log submission is as
follows for each of the 3 labels ERROR : Value is not match with ontology',
value='tmt133n', row=111, column='comment[label].  I checked the OLS PRIDE
controlled vocabulary, and it doesn't show up in the system yet. Is there
something I need to do?

Thanks,
Danelle
